sudo: false
language: node_js
node_js:
  - '6'
  - '7'
script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "7" ]; then
       npm run build;
     fi'
  - 'npm test'
after_script:
  - 'istanbul cover --verbose --dir coverage node_modules/.bin/_mocha scripts/parse-emoji-data.js -- -u exports -R spec && cat coverage/lcov.info | coveralls; rm -rf coverage/lcov*'
git:
  depth: 1
